name: github pages

on:
  workflow_dispatch:
  pull_request:
  push:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Python (pip)
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: .github/workflows/main.yml

      - name: Install poetry
        run: |
          python3 -m pip install --upgrade poetry==2.1.1

      - name: Setup Python (poetry)
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry install

      - run: |
          poetry run mkdocs build
          poetry run python news2rss.py -f site/news/index.html -o site/news.xml

      - name: Upload for pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    concurrency: ci-${{ github.ref }}
    permissions:
      pages: write
      id-token: write
    if: github.repository != 'msys2/msys2.github.io' || (github.event_name != 'pull_request' && github.ref == 'refs/heads/main')
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
